# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /scr2/j/dmx/seqan-trunk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /scr2/j/dmx/seqan-trunk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	cd /scr2/j/dmx/seqan-trunk && /usr/local/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	cd /scr2/j/dmx/seqan-trunk && /usr/local/bin/cpack --config ./CPackSourceConfig.cmake /scr2/j/dmx/seqan-trunk/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	cd /scr2/j/dmx/seqan-trunk && $(CMAKE_COMMAND) -E cmake_progress_start /scr2/j/dmx/seqan-trunk/CMakeFiles /scr2/j/dmx/seqan-trunk/sandbox/jvd/apps/dmx/CMakeFiles/progress.marks
	cd /scr2/j/dmx/seqan-trunk && $(MAKE) -f CMakeFiles/Makefile2 sandbox/jvd/apps/dmx/all
	$(CMAKE_COMMAND) -E cmake_progress_start /scr2/j/dmx/seqan-trunk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /scr2/j/dmx/seqan-trunk && $(MAKE) -f CMakeFiles/Makefile2 sandbox/jvd/apps/dmx/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /scr2/j/dmx/seqan-trunk && $(MAKE) -f CMakeFiles/Makefile2 sandbox/jvd/apps/dmx/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /scr2/j/dmx/seqan-trunk && $(MAKE) -f CMakeFiles/Makefile2 sandbox/jvd/apps/dmx/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /scr2/j/dmx/seqan-trunk && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/rule:
	cd /scr2/j/dmx/seqan-trunk && $(MAKE) -f CMakeFiles/Makefile2 sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/rule
.PHONY : sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/rule

# Convenience name for target.
dmx: sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/rule
.PHONY : dmx

# fast build rule for target.
dmx/fast:
	cd /scr2/j/dmx/seqan-trunk && $(MAKE) -f sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/build.make sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/build
.PHONY : dmx/fast

dmx.o: dmx.cpp.o
.PHONY : dmx.o

# target to build an object file
dmx.cpp.o:
	cd /scr2/j/dmx/seqan-trunk && $(MAKE) -f sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/build.make sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/dmx.cpp.o
.PHONY : dmx.cpp.o

dmx.i: dmx.cpp.i
.PHONY : dmx.i

# target to preprocess a source file
dmx.cpp.i:
	cd /scr2/j/dmx/seqan-trunk && $(MAKE) -f sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/build.make sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/dmx.cpp.i
.PHONY : dmx.cpp.i

dmx.s: dmx.cpp.s
.PHONY : dmx.s

# target to generate assembly for a file
dmx.cpp.s:
	cd /scr2/j/dmx/seqan-trunk && $(MAKE) -f sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/build.make sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/dmx.cpp.s
.PHONY : dmx.cpp.s

dmxBarcode.o: dmxBarcode.cpp.o
.PHONY : dmxBarcode.o

# target to build an object file
dmxBarcode.cpp.o:
	cd /scr2/j/dmx/seqan-trunk && $(MAKE) -f sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/build.make sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/dmxBarcode.cpp.o
.PHONY : dmxBarcode.cpp.o

dmxBarcode.i: dmxBarcode.cpp.i
.PHONY : dmxBarcode.i

# target to preprocess a source file
dmxBarcode.cpp.i:
	cd /scr2/j/dmx/seqan-trunk && $(MAKE) -f sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/build.make sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/dmxBarcode.cpp.i
.PHONY : dmxBarcode.cpp.i

dmxBarcode.s: dmxBarcode.cpp.s
.PHONY : dmxBarcode.s

# target to generate assembly for a file
dmxBarcode.cpp.s:
	cd /scr2/j/dmx/seqan-trunk && $(MAKE) -f sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/build.make sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/dmxBarcode.cpp.s
.PHONY : dmxBarcode.cpp.s

dmxCore.o: dmxCore.cpp.o
.PHONY : dmxCore.o

# target to build an object file
dmxCore.cpp.o:
	cd /scr2/j/dmx/seqan-trunk && $(MAKE) -f sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/build.make sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/dmxCore.cpp.o
.PHONY : dmxCore.cpp.o

dmxCore.i: dmxCore.cpp.i
.PHONY : dmxCore.i

# target to preprocess a source file
dmxCore.cpp.i:
	cd /scr2/j/dmx/seqan-trunk && $(MAKE) -f sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/build.make sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/dmxCore.cpp.i
.PHONY : dmxCore.cpp.i

dmxCore.s: dmxCore.cpp.s
.PHONY : dmxCore.s

# target to generate assembly for a file
dmxCore.cpp.s:
	cd /scr2/j/dmx/seqan-trunk && $(MAKE) -f sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/build.make sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/dmxCore.cpp.s
.PHONY : dmxCore.cpp.s

dmxIO.o: dmxIO.cpp.o
.PHONY : dmxIO.o

# target to build an object file
dmxIO.cpp.o:
	cd /scr2/j/dmx/seqan-trunk && $(MAKE) -f sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/build.make sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/dmxIO.cpp.o
.PHONY : dmxIO.cpp.o

dmxIO.i: dmxIO.cpp.i
.PHONY : dmxIO.i

# target to preprocess a source file
dmxIO.cpp.i:
	cd /scr2/j/dmx/seqan-trunk && $(MAKE) -f sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/build.make sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/dmxIO.cpp.i
.PHONY : dmxIO.cpp.i

dmxIO.s: dmxIO.cpp.s
.PHONY : dmxIO.s

# target to generate assembly for a file
dmxIO.cpp.s:
	cd /scr2/j/dmx/seqan-trunk && $(MAKE) -f sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/build.make sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/dmxIO.cpp.s
.PHONY : dmxIO.cpp.s

dmxRead.o: dmxRead.cpp.o
.PHONY : dmxRead.o

# target to build an object file
dmxRead.cpp.o:
	cd /scr2/j/dmx/seqan-trunk && $(MAKE) -f sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/build.make sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/dmxRead.cpp.o
.PHONY : dmxRead.cpp.o

dmxRead.i: dmxRead.cpp.i
.PHONY : dmxRead.i

# target to preprocess a source file
dmxRead.cpp.i:
	cd /scr2/j/dmx/seqan-trunk && $(MAKE) -f sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/build.make sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/dmxRead.cpp.i
.PHONY : dmxRead.cpp.i

dmxRead.s: dmxRead.cpp.s
.PHONY : dmxRead.s

# target to generate assembly for a file
dmxRead.cpp.s:
	cd /scr2/j/dmx/seqan-trunk && $(MAKE) -f sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/build.make sandbox/jvd/apps/dmx/CMakeFiles/dmx.dir/dmxRead.cpp.s
.PHONY : dmxRead.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... dmx"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... dmx.o"
	@echo "... dmx.i"
	@echo "... dmx.s"
	@echo "... dmxBarcode.o"
	@echo "... dmxBarcode.i"
	@echo "... dmxBarcode.s"
	@echo "... dmxCore.o"
	@echo "... dmxCore.i"
	@echo "... dmxCore.s"
	@echo "... dmxIO.o"
	@echo "... dmxIO.i"
	@echo "... dmxIO.s"
	@echo "... dmxRead.o"
	@echo "... dmxRead.i"
	@echo "... dmxRead.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /scr2/j/dmx/seqan-trunk && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

